apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cbull
  name: slack-go
  labels:
    app: slack-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-go
  template:
    metadata:
      labels:
        app: slack-go
    spec:
      containers:
      - env:
        image: csbull55/slack-go:v1
        name: slack-go
        imagePullPolicy: Always
        volumeMounts:
          - name: slack-volume
            mountPath: /assets/config.json
      volumes:
        - name: slack-volume
          configMap:
            name: slack-config