apiVersion: v1
kind: Service
metadata:
  name: slack-go 
  namespace: cbull
  labels:
    app: slack-go
spec:
  ports:
  - name: metrics 
    port: 2113
    targetPort: 2113
    protocol: TCP 
  selector:
    app: slack-go